[package]
name = "smartmail"
version = "0.1.0"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]

[dependencies]
rumqtt = "0.10"
serde_json = "1.0"
data-encoding = "2.0.0-rc.2"
byteorder = "1.1"
log = "0.3"
env_logger = "0.4"
lazy_static = "0.2"
